min_version = "2026.6.14"

[settings]
dotfiles.default_mode = "symlink"
experimental = true

[tools]
"github:uvu1/dotflow" = "0.1.0"
delta = "latest"
fd = "latest"
fzf = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
rg = "latest"
stylua = "latest"
tree-sitter = "latest"

[dotfiles]
"~/.config/nvim" = { source = "dotfiles/.config/nvim", mode = "symlink" }
"~/.gitconfig" = { source = "dotfiles/.gitconfig.tmpl", mode = "template" }
