[settings]
experimental = true

[tools]
"github:uvu1/dotflow" = "0.1.0"
bat = "latest"
"cargo:eza" = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
helm = "latest"
kubectl = "latest"
neovim = "latest"
starship = "latest"
rg = "latest"
rust = "latest"
gh = "latest"
jq = "latest"
node = "24.15.0"
python = "3.14"
codex = "latest"
stylua = "latest"
lazygit = "latest"
tree-sitter = "latest"
cloudflared = "latest"
zoxide = "latest"
prettier = "latest"
pipx = "latest"
yamllint = "latest"
ruff = "latest"
biome = "latest"
just = "latest"
delta = "latest"
yq = "latest"
claude = "latest"
