[settings]
experimental = true

[tools]
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
helm = "latest"
jqp = "latest"
kubectl = "latest"
neovim = "latest"
starship = "latest"
rg = "latest"
rust = "latest"
gh = "latest"
jq = "latest"
node = "24.15.0"
codex = "latest"
stylua = "latest"
uv = "latest"
lazygit = "latest"
bun = "latest"
tree-sitter = "latest"
cloudflared = "latest"
zoxide = "latest"
prettier = "latest"
yamlfmt = "latest"
yamllint = "latest"
ruff = "latest"
biome = "latest"
just = "latest"
delta = "latest"
yq = "latest"
claude = "latest"
